# Generated by Django 3.2.3 on 2022-01-17 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='users',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='users',
            new_name='user',
        ),
    ]
